#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#	 Malika IHLE & Joel PICK  malika_ihle@hotmail.fr & joel.l.pick@gmail.com
#	 Handling output of simulations running on iceberg 
#	 Start : 22/03/2017
#	 last modif : 22/03/2017
#	 commit: call all files generated by simulation runnin on iceberg
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

rm(list = ls(all = TRUE))

# import files
fileNames <- list.files("Sim1_out") # vector of filenames
fileList <- lapply(paste("Sim1_out",fileNames, sep="/"), read.csv) # list with one file per element named from 1 to 3114
for (i in 1:length(fileList)) {names(fileList)[[i]]<-fileNames[i]} # change name of each element to be their filename

# select files per Sim type
fileList_Sim1_1 <- fileList[grepl("sim1_1",names(fileList))] 
fileList_Sim1_2 <- fileList[grepl("sim1_2",names(fileList))] 
fileList_Sim1_3 <- fileList[grepl("sim1_3",names(fileList))] 
fileList_Sim1_4 <- fileList[grepl("sim1_4",names(fileList))] 
fileList_Sim1_5 <- fileList[grepl("sim1_5",names(fileList))] 
fileList_Sim1_6 <- fileList[grepl("sim1_6",names(fileList))] 

# Number of files per sim type
NreplicatesSimulation <- c(
length(fileList_Sim1_1), # 685
length(fileList_Sim1_2), # 611
length(fileList_Sim1_3), # 279
length(fileList_Sim1_4), # 524
length(fileList_Sim1_5), # 535
length(fileList_Sim1_6)) # 480

# Function counting number of significant result as a percentage of NreplicatesSimulation
Shape_results <- function(MY_Results, TypeNumber){

sorted_results <- lapply(MY_Results, function(x){ 
subx <- x[,-1] 
subx <- subx[ , order(names(subx))] 
cbind(Factor=x[,1], subx)
})

Signi_results <- lapply(sorted_results, function(x){
x_p <- x[,-(1:((ncol(x)+1)/2))]
x_e <- x[,c(-1,-(((ncol(x)-1)/2+2):ncol(x)))]

cbind(x_p < 0.05, x_e)
})

results_Sign_compiled <- Reduce('+',Signi_results)/NreplicatesSimulation[TypeNumber]
results_Sign_compiled <- cbind(results_Sign_compiled[,c(-(((ncol(results_Sign_compiled))/2+1):ncol(results_Sign_compiled)))]*100,
										results_Sign_compiled[,-(1:((ncol(results_Sign_compiled))/2))])
results_PercentageFactorSignificant <- data.frame(Factor=MY_Results[[1]]$Factor,results_Sign_compiled)

return(results_PercentageFactorSignificant)

}

# shape results Sim 1
Results_Sim_1 <- c(
list(Shape_results(fileList_Sim1_1,1)), # no_autocor_no_cor
list(Shape_results(fileList_Sim1_2,2)), # no_autocor_corCN
list(Shape_results(fileList_Sim1_3,3)), # full_autocor_no_cor
list(Shape_results(fileList_Sim1_4,4)), # full_autocor_corCN
list(Shape_results(fileList_Sim1_5,5)), # partial_autocor_no_cor
list(Shape_results(fileList_Sim1_6,6))) # partial_autocor_corCN

Results_Sim_1


# [[1]]
                    # Factor      p_modA p_modA_Ben p_modA_simple   p_modAbin p_modAdev      p_modS p_modSdev        e_modA   e_modA_simple      e_modABen     e_modAbin     e_modAdev
# 1              (Intercept) 100.0000000 100.000000    100.000000 100.0000000 13.722628 100.0000000 27.591241  2.6049199281  2.613141584789  0.44961152050  0.6300994116  0.0410348977
# 2                scale(CN)   0.2919708   4.817518      2.043796   0.2919708  5.547445   0.5839416  4.963504 -0.0000368385 -0.000007278941  0.00002117397 -0.0001568036  0.0005795786
# 3             scale(DiffP) 100.0000000 100.000000    100.000000 100.0000000 13.722628 100.0000000  6.569343 -0.1972775178 -0.191303849565 -0.06547641039  0.5083594025 -0.0504295412
# 4            scale(TotalP) 100.0000000         NA    100.000000 100.0000000 14.014599 100.0000000 11.240876  0.4388103582  0.423560804278             NA -0.1956000829  0.0289445201
# 5               Typez_Obsv   0.0000000         NA            NA   1.0218978        NA   0.5839416        NA  0.0027703829              NA             NA  0.0063308726            NA
# 6     Typez_Obsv:scale(CN)   0.0000000         NA            NA   0.4379562        NA   0.0000000        NA  0.0000394198              NA             NA  0.0001191474            NA
# 7  Typez_Obsv:scale(DiffP)   0.0000000         NA            NA   0.8759124        NA   0.0000000        NA -0.0023549062              NA             NA -0.0072511918            NA
# 8 Typez_Obsv:scale(TotalP)   0.0000000         NA            NA   0.1459854        NA   0.0000000        NA  0.0003823521              NA             NA  0.0005886297            NA
          # e_modS     e_modSdev
# 1  1.92208927254  0.0650012736
# 2  0.00001668071 -0.0006861903
# 3 -0.20924787695 -0.0138037030
# 4  0.64685950043 -0.0018939122
# 5  0.01039874045            NA
# 6 -0.00009227417            NA
# 7  0.00003014308            NA
# 8 -0.00400817531            NA

# [[2]]
                    # Factor p_modA p_modA_Ben p_modA_simple   p_modAbin p_modAdev      p_modS p_modSdev        e_modA e_modA_simple   e_modABen     e_modAbin     e_modAdev        e_modS
# 1              (Intercept)    100        100           100 100.0000000 17.021277 100.0000000 27.495908  2.6275161959    2.63955146  0.46561401  0.5285416579  0.0475636200  1.9328240995
# 2                scale(CN)    100        100           100   0.8183306  6.382979 100.0000000  5.073650  0.0399115057    0.04378969  0.01530365 -0.0014810969  0.0004610251  0.0673756051
# 3             scale(DiffP)    100        100           100 100.0000000 11.456628 100.0000000  7.855974 -0.1346839967   -0.12735401 -0.05487214  0.3984766277 -0.0456470843 -0.1393711498
# 4            scale(TotalP)    100         NA           100 100.0000000 11.783961 100.0000000 10.801964  0.4312410520    0.40495480          NA -0.1764925951  0.0239241204  0.6403946691
# 5               Typez_Obsv      0         NA            NA   1.3093290        NA   0.4909984        NA  0.0033469535            NA          NA  0.0081379888            NA  0.0103260433
# 6     Typez_Obsv:scale(CN)      0         NA            NA   0.3273322        NA   0.0000000        NA -0.0001791847            NA          NA -0.0003902462            NA -0.0015841613
# 7  Typez_Obsv:scale(DiffP)      0         NA            NA   1.4729951        NA   0.0000000        NA -0.0019815356            NA          NA -0.0052887197            NA -0.0001887653
# 8 Typez_Obsv:scale(TotalP)      0         NA            NA   0.3273322        NA   0.0000000        NA  0.0001020930            NA          NA -0.0003930133            NA -0.0028540135
     # e_modSdev
# 1  0.064890367
# 2 -0.001886659
# 3 -0.010832253
# 4 -0.001747153
# 5           NA
# 6           NA
# 7           NA
# 8           NA

# [[3]]
                    # Factor p_modA p_modA_Ben p_modA_simple   p_modAbin  p_modAdev    p_modS  p_modSdev         e_modA e_modA_simple     e_modABen     e_modAbin    e_modAdev         e_modS
# 1              (Intercept)    100  100.00000    100.000000 100.0000000 100.000000 100.00000 100.000000  2.60052675769  2.8254352909  0.5612191121  0.6393256129  4.033776294  1.91081968888
# 2                scale(CN)      0    6.09319      3.225806   0.3584229   6.451613   0.00000   5.376344 -0.00005928784 -0.0004912567 -0.0001833774 -0.0001069042 -0.006986886 -0.00004923149
# 3             scale(DiffP)    100  100.00000    100.000000 100.0000000 100.000000 100.00000 100.000000 -0.20429830080 -0.2715846188 -0.0968193943  0.5187823754 -2.760640223 -0.21784411824
# 4            scale(TotalP)    100         NA    100.000000 100.0000000 100.000000 100.00000 100.000000  0.45106744281  0.5009495789            NA -0.1996583574  3.870659610  0.67030002306
# 5               Typez_Obsv    100         NA            NA 100.0000000         NA 100.00000         NA  0.21956393265            NA            NA  0.8202031198           NA  0.31542292521
# 6     Typez_Obsv:scale(CN)      0         NA            NA   6.8100358         NA   0.00000         NA -0.00043507452            NA            NA -0.0020087768           NA -0.00051831845
# 7  Typez_Obsv:scale(DiffP)    100         NA            NA  13.9784946         NA 100.00000         NA -0.07647280178            NA            NA -0.0117952045           NA -0.04589372432
# 8 Typez_Obsv:scale(TotalP)    100         NA            NA 100.0000000         NA  97.49104         NA  0.06583846677            NA            NA  0.2360138723           NA  0.03207994642
     # e_modSdev
# 1  3.196947151
# 2 -0.004347377
# 3 -1.594921541
# 4  3.107912554
# 5           NA
# 6           NA
# 7           NA
# 8           NA

# [[4]]
                    # Factor      p_modA p_modA_Ben p_modA_simple  p_modAbin p_modAdev      p_modS p_modSdev       e_modA e_modA_simple   e_modABen    e_modAbin   e_modAdev       e_modS e_modSdev
# 1              (Intercept) 100.0000000        100           100 100.000000  100.0000 100.0000000 100.00000  2.621139975    2.86088521  0.58635013  0.535970595  4.55335359  1.917310306  3.541205
# 2                scale(CN)  99.6183206        100           100   1.145038   10.1145 100.0000000  20.99237  0.037822540    0.04635624  0.05088389 -0.001926802 -0.06419492  0.065600368 -0.095543
# 3             scale(DiffP) 100.0000000        100           100 100.000000  100.0000 100.0000000 100.00000 -0.141721683   -0.19809839 -0.08757307  0.410237099 -2.48654624 -0.146997982 -1.375306
# 4            scale(TotalP) 100.0000000         NA           100 100.000000  100.0000 100.0000000 100.00000  0.448068327    0.49466529          NA -0.180232950  4.62170616  0.668396045  3.754620
# 5               Typez_Obsv 100.0000000         NA            NA 100.000000        NA 100.0000000        NA  0.234731214            NA          NA  0.827876798          NA  0.325434032        NA
# 6     Typez_Obsv:scale(CN)   0.9541985         NA            NA  19.083969        NA   0.1908397        NA  0.007016686            NA          NA  0.021277684          NA  0.004346845        NA
# 7  Typez_Obsv:scale(DiffP) 100.0000000         NA            NA  21.946565        NA 100.0000000        NA -0.062500214            NA          NA  0.018455759          NA -0.036062606        NA
# 8 Typez_Obsv:scale(TotalP) 100.0000000         NA            NA 100.000000        NA  77.2900763        NA  0.063078199            NA          NA  0.225524501          NA  0.028810976        NA

# [[5]]
                    # Factor    p_modA p_modA_Ben p_modA_simple p_modAbin p_modAdev    p_modS p_modSdev      e_modA e_modA_simple   e_modABen   e_modAbin e_modAdev      e_modS e_modSdev
# 1              (Intercept) 100.00000        100           100 100.00000       100 100.00000       100  2.56755004    2.74081503  0.51649760  0.51968053  3.075398  1.88007854  2.621137
# 2                scale(CN)  29.53271        100           100  55.70093       100  34.95327       100  0.01131626    0.07947211  0.03989404  0.02484926  1.211475  0.01690917  1.005047
# 3             scale(DiffP) 100.00000        100           100 100.00000       100 100.00000       100 -0.22227778   -0.27338380 -0.08498418  0.40732117 -2.212961 -0.23461235 -1.442569
# 4            scale(TotalP) 100.00000         NA           100 100.00000       100 100.00000       100  0.47243461    0.51865972          NA -0.11374512  3.343506  0.68931884  2.789133
# 5               Typez_Obsv 100.00000         NA            NA 100.00000        NA 100.00000        NA  0.16651513            NA          NA  0.55971725        NA  0.25779031        NA
# 6     Typez_Obsv:scale(CN) 100.00000         NA            NA 100.00000        NA 100.00000        NA  0.06824227            NA          NA  0.28720499        NA  0.09204818        NA
# 7  Typez_Obsv:scale(DiffP) 100.00000         NA            NA  72.89720        NA 100.00000        NA -0.06268774            NA          NA -0.05487060        NA -0.04472892        NA
# 8 Typez_Obsv:scale(TotalP) 100.00000         NA            NA 100.00000        NA 100.00000        NA  0.06593938            NA          NA  0.25212338        NA  0.03888063        NA

# [[6]]
                    # Factor p_modA p_modA_Ben p_modA_simple  p_modAbin p_modAdev    p_modS p_modSdev      e_modA e_modA_simple   e_modABen    e_modAbin e_modAdev      e_modS  e_modSdev
# 1              (Intercept)    100        100           100 100.000000       100 100.00000       100  2.58863351     2.7872679  0.54518192  0.434578798  4.033875  1.88254695  3.4062325
# 2                scale(CN)    100        100           100  67.291667       100 100.00000       100  0.05356655     0.1127643  0.09256697  0.034611151  0.774740  0.09075081  0.5509274
# 3             scale(DiffP)    100        100           100 100.000000       100 100.00000       100 -0.15314903    -0.2029166 -0.08222083  0.340757952 -2.381048 -0.15790286 -1.5158450
# 4            scale(TotalP)    100         NA           100 100.000000       100 100.00000       100  0.46568133     0.5055683          NA -0.118547598  4.619208  0.68525354  3.9153528
# 5               Typez_Obsv    100         NA            NA 100.000000        NA 100.00000        NA  0.19194508            NA          NA  0.633663649        NA  0.28590658         NA
# 6     Typez_Obsv:scale(CN)    100         NA            NA 100.000000        NA 100.00000        NA  0.05812890            NA          NA  0.231877442        NA  0.06880903         NA
# 7  Typez_Obsv:scale(DiffP)    100         NA            NA   7.291667        NA 100.00000        NA -0.05786770            NA          NA  0.001983362        NA -0.03993487         NA
# 8 Typez_Obsv:scale(TotalP)    100         NA            NA 100.000000        NA  53.33333        NA  0.06003517            NA          NA  0.279090547        NA  0.02512728         NA


