#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#	 Malika IHLE & Joel PICK  malika_ihle@hotmail.fr & joel.l.pick@gmail.com
#	 Handling output of simulations running on iceberg 
#	 Start : 22/03/2017
#	 modif : 23/03/2017
#	 commit: call all files generated by simulation running on iceberg - handle Sim2-3 logs > exclude all four types of sims for PbLog23
#  last modif: 20/02/2018
#  commit: explore range of effect for Diff P and Total P for sim 1 mod_A (=mod iv) scenarios _1 to _6 (bearing in mind we are probably in scenario _4)
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

rm(list = ls(all = TRUE))

require(stringr)
library(qdap)
library(dplyr)

# Function counting number of significant result as a percentage of NreplicatesSimulation

Shape_results <- function(MY_Results, TypeNumber){

sorted_results <- lapply(MY_Results, function(x){ 
subx <- x[,-1] 
subx <- subx[ , order(names(subx))] 
cbind(Factor=x[,1], subx)
})

Signi_results <- lapply(sorted_results, function(x){
x_p <- x[,-(1:((ncol(x)+1)/2))]
x_e <- x[,c(-1,-(((ncol(x)-1)/2+2):ncol(x)))]

cbind(x_p < 0.05, x_e)
})

results_Sign_compiled <- Reduce('+',Signi_results)/NreplicatesSimulation[TypeNumber]
results_Sign_compiled <- cbind(results_Sign_compiled[,c(-(((ncol(results_Sign_compiled))/2+1):ncol(results_Sign_compiled)))]*100,
										results_Sign_compiled[,-(1:((ncol(results_Sign_compiled))/2))])
results_Sign_compiled <- round(results_Sign_compiled,2)
results_PercentageFactorSignificant <- data.frame(Factor=MY_Results[[1]]$Factor,results_Sign_compiled)

return(results_PercentageFactorSignificant)

}


Shape_results2 <- function(MY_Results, TypeNumber){ 
  # MY_Results <- fileList_Sim1_1 
  # TypeNumber <- 1
  # x <- MY_Results[[1]]
  effects_modA <- do.call(rbind,lapply(MY_Results, function(x){x$e_modA[c(5:8)]}))
  colnames(effects_modA) <-MY_Results[[1]]$Factor[c(5:8)]
  return(summary(effects_modA))
  
}


Shape_results3 <- function(MY_Results, TypeNumber){ 
  # MY_Results <- fileList_Sim1_1 
  # TypeNumber <- 1
  # x <- MY_Results[[1]]
  effects_modA <- do.call(rbind,lapply(MY_Results, function(x){x$e_modA[c(5:8)]}))
  MeanSDout <- cbind(rbind(mean(effects_modA[,1]), sd(effects_modA[,1])), 
        rbind(mean(effects_modA[,2]), sd(effects_modA[,2])),
        rbind(mean(effects_modA[,3]), sd(effects_modA[,3])),
        rbind(mean(effects_modA[,4]), sd(effects_modA[,4])))
  colnames(MeanSDout) <-MY_Results[[1]]$Factor[c(5:8)]
  rownames(MeanSDout) <- c('Mean','SD')
  return(MeanSDout)
  
}


Shape_results4 <- function(MY_Results, TypeNumber){ 
  # MY_Results <- fileList_Sim1_1 
  # i <- 2
  
  MY_Resultssub <- lapply(MY_Results, function(x){ 
    subx <- x[,c("e_modA_simple", "e_modABen", "e_modAdev","e_modA", "e_modAbin", "e_modS" )] })
  
  mm <- array(NA,dim=c(8,6,length(MY_Resultssub))) # empty array
  for(i in 1:length(MY_Resultssub)) mm[,,i] <- as.matrix(MY_Resultssub[[i]]) # fill in the array with the data frane from the list MY_Resultssub
  dim(mm)
  
 Means <- round(apply(mm,1:2,mean),2)
 LowerCI <- round(apply(mm,1:2,quantile, probs=c(0.025), na.rm=TRUE),2)
 UpperCI <- round(apply(mm,1:2,quantile, probs=c(0.975), na.rm=TRUE),2)

table <- matrix( paste(paste(as.character(Means), LowerCI, sep= "["), ";", UpperCI, "]", sep=""), nrow=8, ncol = 6)

Table <- cbind(data.frame(MY_Results[[1]]$Factor), data.frame(table))
  colnames(Table) <- c("Factor", "e_modA_simple", "e_modABen", "e_modAdev","e_modA", "e_modAbin", "e_modS")

return(Table)  
  }


{# Sim 1

# import log files
fileNamesLog <- list.files("Iceberg/Sim1_log") # vector of filenames
Logs <- do.call(rbind,lapply(paste("Iceberg/Sim1_log",fileNamesLog, sep="/"), FUN= function(x){str_c(readLines(x), collapse = " ")}))
Logs[1]
Logs <- gsub("^.*union","_",Logs) # only keep the warning which come after log of packages loaded
Logs <- data.frame(FileName=fileNamesLog, Log = Logs)
PbLogs <- Logs$FileName[Logs$Log != "_ "] # 547 sim where one model did not converge
PbLogs_Type <- gsub("\\..*","",PbLogs) # sim type where models did not converge

table(PbLogs_Type)
# models did not converge in those x cases out of 1000
# sim_1_1 sim_1_2 sim_1_3 sim_1_4 sim_1_5 sim_1_6 
#	 37      35     203     189      77       8

PbLogs_sim <- paste(beg2char(PbLogs, ".", 1),char2end(PbLogs, ".", 3), sep="_")# sim name where model did not converge
PbLogs_sim <- paste("sim1", char2end(PbLogs_sim, "_", 2), sep="_")

# import files
fileNames <- list.files("Iceberg/Sim1_out") # vector of filenames
fileList <- lapply(paste("Iceberg/Sim1_out",fileNames, sep="/"), read.csv) # list with one file per element named from 1 to 6000
for (i in 1:length(fileList)) {names(fileList)[[i]]<-gsub("\\..*","",fileNames[i])} # change name of each element to be the sim name
fileList <- fileList[!names(fileList) %in% PbLogs_sim] # remove filenames where one model did not converge

# select files per Sim type
fileList_Sim1_1 <- fileList[grepl("sim1_1",names(fileList))] 
fileList_Sim1_2 <- fileList[grepl("sim1_2",names(fileList))] 
fileList_Sim1_3 <- fileList[grepl("sim1_3",names(fileList))] 
fileList_Sim1_4 <- fileList[grepl("sim1_4",names(fileList))] 
fileList_Sim1_5 <- fileList[grepl("sim1_5",names(fileList))] 
fileList_Sim1_6 <- fileList[grepl("sim1_6",names(fileList))] 

# Number of files per sim type
NreplicatesSimulation <- c(
length(fileList_Sim1_1), # 963
length(fileList_Sim1_2), # 965
length(fileList_Sim1_3), # 797
length(fileList_Sim1_4), # 811
length(fileList_Sim1_5), # 923
length(fileList_Sim1_6)) # 992

      #1
      binom.test(61,963,0.05) # more than 61 becomes significant: accepted false positive rate in simulation 1 = 6.1
      #2
      binom.test(61,965,0.05)# more than 61 becomes significant
      #3
      binom.test(52,797,0.05)# more than 52 becomes significant
      #4
      binom.test(53,811,0.05)# more than 53 becomes significant
      #5
      binom.test(59,923,0.05)# more than 59 becomes significant
      #6
      binom.test(63,992,0.05)# more than 63 becomes significant
      
      mean(c(61,61,52,53,59,63))



# shape results Sim 1
Results_Sim_1 <- c(
list(Shape_results(fileList_Sim1_1,1)), # no_autocor_no_cor
list(Shape_results(fileList_Sim1_2,2)), # no_autocor_corCN
list(Shape_results(fileList_Sim1_3,3)), # full_autocor_no_cor
list(Shape_results(fileList_Sim1_4,4)), # full_autocor_corCN
list(Shape_results(fileList_Sim1_5,5)), # partial_autocor_no_cor
list(Shape_results(fileList_Sim1_6,6))) # partial_autocor_corCN

summary(
  c(
    length(fileList_Sim1_2), 
length(fileList_Sim1_3),
length(fileList_Sim1_4), 
length(fileList_Sim1_5), 
length(fileList_Sim1_6)))

Results_Sim_1
# Simulation 1: Take observed CN ; generate TP either correlated to CN or not ; with or without an effect of CN on A (i.e. with CN = sorting parameter of intervals)


# [[1]]
                    # Factor p_modA p_modA_Ben p_modA_simple p_modAbin p_modAdev p_modS p_modSdev e_modA e_modA_simple e_modABen e_modAbin e_modAdev e_modS e_modSdev
# 1              (Intercept) 100.00     100.00         100.0    100.00     12.95 100.00     26.84   2.61          2.61      0.45      0.63      0.04   1.92      0.06
# 2                scale(CN)   0.41       5.28           2.9      0.31      5.49   0.83      5.28   0.00          0.00      0.00      0.00      0.00   0.00      0.00
# 3             scale(DiffP) 100.00     100.00         100.0    100.00     13.47 100.00      7.46  -0.20         -0.19     -0.07      0.51     -0.05  -0.21     -0.01
# 4            scale(TotalP) 100.00         NA         100.0    100.00     14.09 100.00     11.30   0.44          0.42        NA     -0.20      0.03   0.65      0.00
# 5               Typez_Obsv   0.00         NA            NA      0.83        NA   0.52        NA   0.00            NA        NA      0.01        NA   0.01        NA
# 6     Typez_Obsv:scale(CN)   0.00         NA            NA      0.31        NA   0.00        NA   0.00            NA        NA      0.00        NA   0.00        NA
# 7  Typez_Obsv:scale(DiffP)   0.00         NA            NA      1.14        NA   0.00        NA   0.00            NA        NA     -0.01        NA   0.00        NA
# 8 Typez_Obsv:scale(TotalP)   0.00         NA            NA      0.21        NA   0.00        NA   0.00            NA        NA      0.00        NA   0.00        NA

# [[2]]
                    # Factor p_modA p_modA_Ben p_modA_simple p_modAbin p_modAdev p_modS p_modSdev e_modA e_modA_simple e_modABen e_modAbin e_modAdev e_modS e_modSdev
# 1              (Intercept)    100        100           100    100.00     16.27 100.00     28.19   2.63          2.64      0.47      0.53      0.05   1.93      0.06
# 2                scale(CN)    100        100           100      0.62      5.70 100.00      3.94   0.04          0.04      0.02      0.00      0.00   0.07      0.00
# 3             scale(DiffP)    100        100           100    100.00     13.89 100.00      8.70  -0.13         -0.13     -0.05      0.40     -0.04  -0.14     -0.01
# 4            scale(TotalP)    100         NA           100    100.00     12.85 100.00     12.95   0.43          0.40        NA     -0.18      0.02   0.64      0.00
# 5               Typez_Obsv      0         NA            NA      1.45        NA   0.62        NA   0.00            NA        NA      0.01        NA   0.01        NA
# 6     Typez_Obsv:scale(CN)      0         NA            NA      0.31        NA   0.00        NA   0.00            NA        NA      0.00        NA   0.00        NA
# 7  Typez_Obsv:scale(DiffP)      0         NA            NA      0.93        NA   0.00        NA   0.00            NA        NA     -0.01        NA   0.00        NA
# 8 Typez_Obsv:scale(TotalP)      0         NA            NA      0.31        NA   0.00        NA   0.00            NA        NA      0.00        NA   0.00        NA

# [[3]]
                    # Factor p_modA p_modA_Ben p_modA_simple p_modAbin p_modAdev p_modS p_modSdev e_modA e_modA_simple e_modABen e_modAbin e_modAdev e_modS e_modSdev
# 1              (Intercept) 100.00     100.00        100.00    100.00    100.00 100.00    100.00   2.60          2.83      0.56      0.64      4.03   1.91      3.20
# 2                scale(CN)   0.38       4.02          4.64      0.38      4.89   0.38      4.14   0.00          0.00      0.00      0.00      0.00   0.00      0.00
# 3             scale(DiffP) 100.00     100.00        100.00    100.00    100.00 100.00    100.00  -0.20         -0.27     -0.10      0.52     -2.77  -0.22     -1.60
# 4            scale(TotalP) 100.00         NA        100.00    100.00    100.00 100.00    100.00   0.45          0.50        NA     -0.20      3.88   0.67      3.12
# 5               Typez_Obsv 100.00         NA            NA    100.00        NA 100.00        NA   0.22            NA        NA      0.82        NA   0.32        NA
# 6     Typez_Obsv:scale(CN)   0.00         NA            NA      5.65        NA   0.00        NA   0.00            NA        NA      0.00        NA   0.00        NA
# 7  Typez_Obsv:scale(DiffP) 100.00         NA            NA     13.17        NA 100.00        NA  -0.08            NA        NA     -0.01        NA  -0.05        NA
# 8 Typez_Obsv:scale(TotalP) 100.00         NA            NA    100.00        NA  97.62        NA   0.07            NA        NA      0.24        NA   0.03        NA

# [[4]]
                    # Factor p_modA p_modA_Ben p_modA_simple p_modAbin p_modAdev p_modS p_modSdev e_modA e_modA_simple e_modABen e_modAbin e_modAdev e_modS e_modSdev
# 1              (Intercept) 100.00        100           100    100.00    100.00 100.00     100.0   2.62          2.86      0.59      0.54      4.56   1.92      3.55
# 2                scale(CN)  99.88        100           100      0.74     12.33 100.00      21.7   0.04          0.05      0.05      0.00     -0.07   0.07     -0.10
# 3             scale(DiffP) 100.00        100           100    100.00    100.00 100.00     100.0  -0.14         -0.20     -0.09      0.41     -2.48  -0.15     -1.37
# 4            scale(TotalP) 100.00         NA           100    100.00    100.00 100.00     100.0   0.45          0.49        NA     -0.18      4.63   0.67      3.77
# 5               Typez_Obsv 100.00         NA            NA    100.00        NA 100.00        NA   0.24            NA        NA      0.83        NA   0.33        NA
# 6     Typez_Obsv:scale(CN)   0.62         NA            NA     18.37        NA   0.12        NA   0.01            NA        NA      0.02        NA   0.00        NA
# 7  Typez_Obsv:scale(DiffP) 100.00         NA            NA     22.56        NA 100.00        NA  -0.06            NA        NA      0.02        NA  -0.04        NA
# 8 Typez_Obsv:scale(TotalP) 100.00         NA            NA    100.00        NA  77.19        NA   0.06            NA        NA      0.23        NA   0.03        NA

# [[5]]
                    # Factor p_modA p_modA_Ben p_modA_simple p_modAbin p_modAdev p_modS p_modSdev e_modA e_modA_simple e_modABen e_modAbin e_modAdev e_modS e_modSdev
# 1              (Intercept) 100.00        100           100    100.00       100 100.00       100   2.57          2.74      0.52      0.52      3.08   1.88      2.62
# 2                scale(CN)  27.19        100           100     54.17       100  31.85       100   0.01          0.08      0.04      0.02      1.21   0.02      1.00
# 3             scale(DiffP) 100.00        100           100    100.00       100 100.00       100  -0.22         -0.27     -0.08      0.41     -2.21  -0.23     -1.44
# 4            scale(TotalP) 100.00         NA           100    100.00       100 100.00       100   0.47          0.52        NA     -0.11      3.35   0.69      2.80
# 5               Typez_Obsv 100.00         NA            NA    100.00        NA 100.00        NA   0.17            NA        NA      0.56        NA   0.26        NA
# 6     Typez_Obsv:scale(CN) 100.00         NA            NA    100.00        NA 100.00        NA   0.07            NA        NA      0.29        NA   0.09        NA
# 7  Typez_Obsv:scale(DiffP) 100.00         NA            NA     73.35        NA 100.00        NA  -0.06            NA        NA     -0.06        NA  -0.04        NA
# 8 Typez_Obsv:scale(TotalP) 100.00         NA            NA    100.00        NA 100.00        NA   0.07            NA        NA      0.25        NA   0.04        NA

# [[6]]
                    # Factor p_modA p_modA_Ben p_modA_simple p_modAbin p_modAdev p_modS p_modSdev e_modA e_modA_simple e_modABen e_modAbin e_modAdev e_modS e_modSdev
# 1              (Intercept)    100        100           100    100.00       100 100.00       100   2.59          2.79      0.55      0.43      4.04   1.88      3.41
# 2                scale(CN)    100        100           100     68.15       100 100.00       100   0.05          0.11      0.09      0.03      0.78   0.09      0.55
# 3             scale(DiffP)    100        100           100    100.00       100 100.00       100  -0.15         -0.20     -0.08      0.34     -2.38  -0.16     -1.51
# 4            scale(TotalP)    100         NA           100    100.00       100 100.00       100   0.47          0.50        NA     -0.12      4.62   0.68      3.92
# 5               Typez_Obsv    100         NA            NA    100.00        NA 100.00        NA   0.19            NA        NA      0.63        NA   0.29        NA
# 6     Typez_Obsv:scale(CN)    100         NA            NA    100.00        NA 100.00        NA   0.06            NA        NA      0.23        NA   0.07        NA
# 7  Typez_Obsv:scale(DiffP)    100         NA            NA      7.56        NA 100.00        NA  -0.06            NA        NA      0.00        NA  -0.04        NA
# 8 Typez_Obsv:scale(TotalP)    100         NA            NA    100.00        NA  51.81        NA   0.06            NA        NA      0.28        NA   0.02        NA


# shape results2 Sim 1 - summary effects for modA
Results2_Sim_1 <- c(
  list(Shape_results2(fileList_Sim1_1,1)), # no_autocor_no_cor
  list(Shape_results2(fileList_Sim1_2,2)), # no_autocor_corCN
  list(Shape_results2(fileList_Sim1_3,3)), # full_autocor_no_cor
  list(Shape_results2(fileList_Sim1_4,4)), # full_autocor_corCN
  list(Shape_results2(fileList_Sim1_5,5)), # partial_autocor_no_cor
  list(Shape_results2(fileList_Sim1_6,6))) # partial_autocor_corCN

Results2_Sim_1

# [[1]]
# Typez_Obsv         Typez_Obsv:scale(CN) Typez_Obsv:scale(DiffP) Typez_Obsv:scale(TotalP)
# Min.   :-0.0093691   Min.   :-1.130e-02   Min.   :-0.012206       Min.   :-0.0098004      
# 1st Qu.: 0.0003543   1st Qu.:-2.425e-03   1st Qu.:-0.004158       1st Qu.:-0.0018937      
# Median : 0.0027801   Median : 3.497e-05   Median :-0.002217       Median : 0.0002098      
# Mean   : 0.0027825   Mean   :-3.550e-05   Mean   :-0.002271       Mean   : 0.0002529      
# 3rd Qu.: 0.0052727   3rd Qu.: 2.417e-03   3rd Qu.:-0.000175       3rd Qu.: 0.0024322      
# Max.   : 0.0137022   Max.   : 1.093e-02   Max.   : 0.007535       Max.   : 0.0119775      
# 
# [[2]]
# Typez_Obsv         Typez_Obsv:scale(CN) Typez_Obsv:scale(DiffP) Typez_Obsv:scale(TotalP)
# Min.   :-0.0090423   Min.   :-1.317e-02   Min.   :-0.0118199      Min.   :-1.260e-02      
# 1st Qu.: 0.0007844   1st Qu.:-3.298e-03   1st Qu.:-0.0041384      1st Qu.:-2.555e-03      
# Median : 0.0032332   Median :-9.521e-05   Median :-0.0019254      Median :-1.585e-04      
# Mean   : 0.0032400   Mean   :-8.230e-05   Mean   :-0.0019324      Mean   : 2.948e-05      
# 3rd Qu.: 0.0056429   3rd Qu.: 2.897e-03   3rd Qu.: 0.0002262      3rd Qu.: 2.785e-03      
# Max.   : 0.0174860   Max.   : 1.523e-02   Max.   : 0.0079131      Max.   : 1.310e-02      
# 
# [[3]]
# Typez_Obsv     Typez_Obsv:scale(CN) Typez_Obsv:scale(DiffP) Typez_Obsv:scale(TotalP)
# Min.   :0.2041   Min.   :-0.0122434   Min.   :-0.08956        Min.   :0.05262         
# 1st Qu.:0.2167   1st Qu.:-0.0025517   1st Qu.:-0.07956        1st Qu.:0.06296         
# Median :0.2194   Median :-0.0003028   Median :-0.07658        Median :0.06589         
# Mean   :0.2195   Mean   :-0.0001331   Mean   :-0.07656        Mean   :0.06595         
# 3rd Qu.:0.2224   3rd Qu.: 0.0023514   3rd Qu.:-0.07345        3rd Qu.:0.06872         
# Max.   :0.2333   Max.   : 0.0111210   Max.   :-0.06268        Max.   :0.07779         
# 
# [[4]]
# Typez_Obsv     Typez_Obsv:scale(CN) Typez_Obsv:scale(DiffP) Typez_Obsv:scale(TotalP)
# Min.   :0.2207   Min.   :-0.011645    Min.   :-0.07774        Min.   :0.03879         
# 1st Qu.:0.2320   1st Qu.: 0.003406    1st Qu.:-0.06507        1st Qu.:0.05922         
# Median :0.2352   Median : 0.006593    Median :-0.06224        Median :0.06314         
# Mean   :0.2350   Mean   : 0.006728    Mean   :-0.06226        Mean   :0.06300         
# 3rd Qu.:0.2379   3rd Qu.: 0.009964    3rd Qu.:-0.05940        3rd Qu.:0.06748         
# Max.   :0.2494   Max.   : 0.026742    Max.   :-0.04986        Max.   :0.08053         
# 
# [[5]]
# Typez_Obsv     Typez_Obsv:scale(CN) Typez_Obsv:scale(DiffP) Typez_Obsv:scale(TotalP)
# Min.   :0.1538   Min.   :0.05616      Min.   :-0.07751        Min.   :0.04959         
# 1st Qu.:0.1636   1st Qu.:0.06553      1st Qu.:-0.06558        1st Qu.:0.06329         
# Median :0.1665   Median :0.06826      Median :-0.06237        Median :0.06592         
# Mean   :0.1664   Mean   :0.06818      Mean   :-0.06265        Mean   :0.06596         
# 3rd Qu.:0.1693   3rd Qu.:0.07100      3rd Qu.:-0.05968        3rd Qu.:0.06891         
# Max.   :0.1793   Max.   :0.07877      Max.   :-0.04946        Max.   :0.08233         
# 
# [[6]]
# Typez_Obsv     Typez_Obsv:scale(CN) Typez_Obsv:scale(DiffP) Typez_Obsv:scale(TotalP)
# Min.   :0.1781   Min.   :0.04292      Min.   :-0.07291        Min.   :0.02767         
# 1st Qu.:0.1894   1st Qu.:0.05456      1st Qu.:-0.06088        1st Qu.:0.05579         
# Median :0.1922   Median :0.05834      Median :-0.05764        Median :0.05981         
# Mean   :0.1922   Mean   :0.05824      Mean   :-0.05767        Mean   :0.05974         
# 3rd Qu.:0.1950   3rd Qu.:0.06185      3rd Qu.:-0.05468        3rd Qu.:0.06433         
# Max.   :0.2050   Max.   :0.08222      Max.   :-0.04052        Max.   :0.07770  


# shape results3 Sim 1 - summary effects for modA
Results3_Sim_1 <- c(
  list(Shape_results3(fileList_Sim1_1,1)), # no_autocor_no_cor
  list(Shape_results3(fileList_Sim1_2,2)), # no_autocor_corCN
  list(Shape_results3(fileList_Sim1_3,3)), # full_autocor_no_cor
  list(Shape_results3(fileList_Sim1_4,4)), # full_autocor_corCN
  list(Shape_results3(fileList_Sim1_5,5)), # partial_autocor_no_cor
  list(Shape_results3(fileList_Sim1_6,6))) # partial_autocor_corCN

Results3_Sim_1


# shape results4 Sim 1 - summary effects for all models
Results4_Sim_1 <- c(
  list(Shape_results4(fileList_Sim1_1,1)), # no_autocor_no_cor
  list(Shape_results4(fileList_Sim1_2,2)), # no_autocor_corCN
  list(Shape_results4(fileList_Sim1_3,3)), # full_autocor_no_cor
  list(Shape_results4(fileList_Sim1_4,4)), # full_autocor_corCN
  list(Shape_results4(fileList_Sim1_5,5)), # partial_autocor_no_cor
  list(Shape_results4(fileList_Sim1_6,6))) # partial_autocor_corCN


{
  # [[1]]
  # Factor      e_modA_simple          e_modABen         e_modAdev            e_modA         e_modAbin             e_modS
  # 1              (Intercept)    2.61[2.59;2.64]    0.45[0.44;0.46]  0.04[-0.06;0.14]   2.61[2.58;2.63]    0.63[0.6;0.66]    1.92[1.89;1.96]
  # 2                scale(CN)      0[-0.01;0.01]             0[0;0]     0[-0.11;0.09]     0[-0.01;0.01]     0[-0.02;0.02]      0[-0.01;0.01]
  # 3             scale(DiffP) -0.19[-0.22;-0.16] -0.07[-0.07;-0.06] -0.05[-0.18;0.07] -0.2[-0.22;-0.17]   0.51[0.47;0.55] -0.21[-0.25;-0.17]
  # 4            scale(TotalP)     0.42[0.4;0.45]          NA[NA;NA]  0.03[-0.12;0.18]   0.44[0.42;0.46] -0.2[-0.22;-0.17]    0.65[0.62;0.68]
  # 5               Typez_Obsv          NA[NA;NA]          NA[NA;NA]         NA[NA;NA]         0[0;0.01]  0.01[-0.02;0.03]       0.01[0;0.02]
  # 6     Typez_Obsv:scale(CN)          NA[NA;NA]          NA[NA;NA]         NA[NA;NA]     0[-0.01;0.01]     0[-0.02;0.02]      0[-0.01;0.01]
  # 7  Typez_Obsv:scale(DiffP)          NA[NA;NA]          NA[NA;NA]         NA[NA;NA]        0[-0.01;0] -0.01[-0.04;0.02]      0[-0.01;0.01]
  # 8 Typez_Obsv:scale(TotalP)          NA[NA;NA]          NA[NA;NA]         NA[NA;NA]     0[-0.01;0.01]     0[-0.02;0.02]      0[-0.01;0.01]
  # 
  # [[2]]
  # Factor     e_modA_simple          e_modABen         e_modAdev             e_modA          e_modAbin             e_modS
  # 1              (Intercept)   2.64[2.62;2.66]    0.47[0.46;0.47]  0.05[-0.06;0.15]    2.63[2.61;2.65]     0.53[0.5;0.55]     1.93[1.9;1.96]
  # 2                scale(CN)   0.04[0.03;0.07]    0.02[0.01;0.02]     0[-0.14;0.14]    0.04[0.03;0.06]      0[-0.02;0.02]    0.07[0.05;0.09]
  # 3             scale(DiffP) -0.13[-0.15;-0.1] -0.05[-0.06;-0.05] -0.04[-0.17;0.08] -0.13[-0.16;-0.11]     0.4[0.37;0.43] -0.14[-0.17;-0.11]
  # 4            scale(TotalP)    0.4[0.38;0.43]          NA[NA;NA]  0.02[-0.17;0.21]    0.43[0.41;0.45] -0.18[-0.21;-0.15]    0.64[0.61;0.67]
  # 5               Typez_Obsv         NA[NA;NA]          NA[NA;NA]         NA[NA;NA]          0[0;0.01]   0.01[-0.01;0.03]       0.01[0;0.02]
  # 6     Typez_Obsv:scale(CN)         NA[NA;NA]          NA[NA;NA]         NA[NA;NA]      0[-0.01;0.01]      0[-0.02;0.02]      0[-0.02;0.01]
  # 7  Typez_Obsv:scale(DiffP)         NA[NA;NA]          NA[NA;NA]         NA[NA;NA]         0[-0.01;0]  -0.01[-0.03;0.02]      0[-0.01;0.01]
  # 8 Typez_Obsv:scale(TotalP)         NA[NA;NA]          NA[NA;NA]         NA[NA;NA]      0[-0.01;0.01]      0[-0.02;0.02]      0[-0.01;0.01]
  # 
  # [[3]]
  # Factor     e_modA_simple        e_modABen         e_modAdev             e_modA         e_modAbin             e_modS
  # 1              (Intercept)    2.83[2.8;2.85]  0.56[0.55;0.57]   4.03[3.83;4.23]     2.6[2.58;2.62]   0.64[0.61;0.67]    1.91[1.88;1.95]
  # 2                scale(CN)     0[-0.01;0.01]    0[-0.01;0.01]     0[-0.13;0.13]      0[-0.01;0.01]     0[-0.02;0.02]      0[-0.01;0.01]
  # 3             scale(DiffP) -0.27[-0.3;-0.24] -0.1[-0.1;-0.09] -2.77[-3.05;-2.5]  -0.2[-0.23;-0.18]   0.52[0.48;0.57] -0.22[-0.26;-0.19]
  # 4            scale(TotalP)    0.5[0.48;0.53]        NA[NA;NA]    3.88[3.57;4.2]    0.45[0.43;0.47] -0.2[-0.23;-0.17]     0.67[0.64;0.7]
  # 5               Typez_Obsv         NA[NA;NA]        NA[NA;NA]         NA[NA;NA]    0.22[0.21;0.23]   0.82[0.78;0.86]     0.32[0.3;0.33]
  # 6     Typez_Obsv:scale(CN)         NA[NA;NA]        NA[NA;NA]         NA[NA;NA]      0[-0.01;0.01]     0[-0.03;0.03]      0[-0.01;0.01]
  # 7  Typez_Obsv:scale(DiffP)         NA[NA;NA]        NA[NA;NA]         NA[NA;NA] -0.08[-0.09;-0.07] -0.01[-0.07;0.05] -0.05[-0.06;-0.04]
  # 8 Typez_Obsv:scale(TotalP)         NA[NA;NA]        NA[NA;NA]         NA[NA;NA]    0.07[0.06;0.07]   0.24[0.19;0.28]    0.03[0.02;0.04]
  # 
  # [[4]]
  # Factor     e_modA_simple          e_modABen          e_modAdev             e_modA          e_modAbin             e_modS
  # 1              (Intercept)   2.86[2.84;2.88]    0.59[0.58;0.59]    4.56[4.35;4.76]     2.62[2.6;2.64]    0.54[0.51;0.56]    1.92[1.89;1.95]
  # 2                scale(CN)   0.05[0.03;0.07]    0.05[0.04;0.06]  -0.07[-0.26;0.11]    0.04[0.03;0.05]      0[-0.03;0.02]    0.07[0.05;0.09]
  # 3             scale(DiffP) -0.2[-0.22;-0.17] -0.09[-0.09;-0.08] -2.48[-2.76;-2.23] -0.14[-0.16;-0.12]    0.41[0.38;0.44] -0.15[-0.18;-0.12]
  # 4            scale(TotalP)   0.49[0.47;0.52]          NA[NA;NA]    4.63[4.25;5.03]    0.45[0.43;0.47] -0.18[-0.22;-0.15]     0.67[0.64;0.7]
  # 5               Typez_Obsv         NA[NA;NA]          NA[NA;NA]          NA[NA;NA]    0.24[0.23;0.24]    0.83[0.79;0.87]    0.33[0.31;0.34]
  # 6     Typez_Obsv:scale(CN)         NA[NA;NA]          NA[NA;NA]          NA[NA;NA]       0.01[0;0.02]   0.02[-0.03;0.07]      0[-0.01;0.02]
  # 7  Typez_Obsv:scale(DiffP)         NA[NA;NA]          NA[NA;NA]          NA[NA;NA] -0.06[-0.07;-0.05]   0.02[-0.03;0.07] -0.04[-0.05;-0.03]
  # 8 Typez_Obsv:scale(TotalP)         NA[NA;NA]          NA[NA;NA]          NA[NA;NA]    0.06[0.05;0.07]    0.23[0.17;0.28]    0.03[0.02;0.04]
  # 
  # [[5]]
  # Factor     e_modA_simple          e_modABen          e_modAdev             e_modA          e_modAbin             e_modS
  # 1              (Intercept)   2.74[2.71;2.77]    0.52[0.51;0.52]     3.08[2.9;3.26]    2.57[2.55;2.59]    0.52[0.49;0.55]    1.88[1.85;1.92]
  # 2                scale(CN)   0.08[0.07;0.09]    0.04[0.03;0.05]    1.21[1.07;1.35]       0.01[0;0.02]    0.02[0.01;0.04]       0.02[0;0.03]
  # 3             scale(DiffP) -0.27[-0.3;-0.24] -0.08[-0.09;-0.08] -2.21[-2.46;-1.97]  -0.22[-0.25;-0.2]    0.41[0.38;0.44]  -0.23[-0.27;-0.2]
  # 4            scale(TotalP)   0.52[0.49;0.54]          NA[NA;NA]    3.35[3.05;3.67]     0.47[0.45;0.5] -0.11[-0.14;-0.09]    0.69[0.66;0.72]
  # 5               Typez_Obsv         NA[NA;NA]          NA[NA;NA]          NA[NA;NA]    0.17[0.16;0.17]    0.56[0.53;0.59]    0.26[0.25;0.27]
  # 6     Typez_Obsv:scale(CN)         NA[NA;NA]          NA[NA;NA]          NA[NA;NA]    0.07[0.06;0.08]    0.29[0.26;0.32]     0.09[0.08;0.1]
  # 7  Typez_Obsv:scale(DiffP)         NA[NA;NA]          NA[NA;NA]          NA[NA;NA] -0.06[-0.07;-0.05]  -0.06[-0.1;-0.01] -0.04[-0.06;-0.03]
  # 8 Typez_Obsv:scale(TotalP)         NA[NA;NA]          NA[NA;NA]          NA[NA;NA]    0.07[0.06;0.07]    0.25[0.21;0.29]    0.04[0.03;0.05]
  # 
  # [[6]]
  # Factor     e_modA_simple          e_modABen          e_modAdev             e_modA          e_modAbin             e_modS
  # 1              (Intercept)   2.79[2.76;2.81]    0.55[0.54;0.55]    4.04[3.84;4.24]    2.59[2.57;2.61]    0.43[0.41;0.46]    1.88[1.85;1.91]
  # 2                scale(CN)    0.11[0.1;0.14]     0.09[0.09;0.1]    0.78[0.58;0.95]    0.05[0.04;0.07]    0.03[0.01;0.06]    0.09[0.07;0.12]
  # 3             scale(DiffP) -0.2[-0.23;-0.17] -0.08[-0.09;-0.08] -2.38[-2.65;-2.11] -0.15[-0.18;-0.13]    0.34[0.32;0.37] -0.16[-0.19;-0.13]
  # 4            scale(TotalP)    0.5[0.48;0.53]          NA[NA;NA]    4.62[4.23;5.04]    0.47[0.44;0.49] -0.12[-0.15;-0.09]    0.68[0.65;0.72]
  # 5               Typez_Obsv         NA[NA;NA]          NA[NA;NA]          NA[NA;NA]     0.19[0.18;0.2]    0.63[0.61;0.66]     0.29[0.27;0.3]
  # 6     Typez_Obsv:scale(CN)         NA[NA;NA]          NA[NA;NA]          NA[NA;NA]    0.06[0.05;0.07]    0.23[0.19;0.27]    0.07[0.05;0.08]
  # 7  Typez_Obsv:scale(DiffP)         NA[NA;NA]          NA[NA;NA]          NA[NA;NA] -0.06[-0.07;-0.05]      0[-0.04;0.05] -0.04[-0.05;-0.03]
  # 8 Typez_Obsv:scale(TotalP)         NA[NA;NA]          NA[NA;NA]          NA[NA;NA]    0.06[0.05;0.07]    0.28[0.22;0.33]    0.02[0.01;0.04]
  # 
}


}

{## Log Sim23

# import log files
fileNamesLog23 <- list.files("Iceberg/Sim23_log") # vector of filenames
Logs23 <- do.call(rbind,lapply(paste("Iceberg/Sim23_log",fileNamesLog23, sep="/"), FUN= function(x){str_c(readLines(x), collapse = " ")}))
Logs23[1]
Logs23 <- gsub("^.*union","_",Logs23) # only keep the warning which come after log of packages loaded
Logs23 <- data.frame(FileName=fileNamesLog23, Log = Logs23)
PbLogs23 <- Logs23$FileName[Logs23$Log != "_ "] # 252 sim where one model did not converge
PbLogs_Type23 <- gsub("\\..*","",PbLogs23) # sim type where models did not converge

table(PbLogs_Type23)
# models did not converge in those x cases out of 1000*4
# sim_23 
#   252

PbLogs_sim23 <- paste(beg2char(PbLogs23, ".", 1),char2end(PbLogs23, ".", 3), sep="_")# sim name where something went wrong
PbLogs_sim23 <- char2end(PbLogs_sim23, "_", 2) # to remove filenames where one model did not converge in any of the four type of simulations

Logs23$Log[Logs23$Log != "_ "] # see the logs: they are model convergence problemes but also data.frame construction problems
Logs23[984,]


}

{# Sim 2

# import files
fileNames2 <- list.files("Iceberg/Sim2_out") # vector of filenames
fileList2 <- lapply(paste("Iceberg/Sim2_out",fileNames2, sep="/"), read.csv) # list with one file per element named from 1 to 6000
for (i in 1:length(fileList2)) {names(fileList2)[[i]]<-gsub("\\..*","",fileNames2[i])} # change name of each element to be the sim name
fileList2 <- fileList2[!char2end(names(fileList2), "_", 2) %in% PbLogs_sim23] # remove filenames where one model did not converge in any of the four type of simulations

# select files per Sim type
fileList_Sim2_1 <- fileList2[grepl("sim2_1",names(fileList2))] 
fileList_Sim2_3 <- fileList2[grepl("sim2_3",names(fileList2))] 
fileList_Sim2_5 <- fileList2[grepl("sim2_5",names(fileList2))] 

# Number of files per sim type
NreplicatesSimulation <- c(
length(fileList_Sim2_1), # 748
0,
length(fileList_Sim2_3), # 748
0,
length(fileList_Sim2_5)) # 748

# shape results Sim 2
Results_Sim_2 <- c(
list(Shape_results(fileList_Sim2_1,1)), # no_autocor
list(Shape_results(fileList_Sim2_3,3)), # full_autocor
list(Shape_results(fileList_Sim2_5,5))) # partial_autocor


Results_Sim_2
# Simulation 2: Take observed CN ; take observed TP ; generate visits ; with or without an effect of CN on A (i.e. with CN = sorting parameter of intervals)


# [[1]]
                    # Factor p_modA p_modA_Ben p_modA_simple p_modAbin p_modAdev p_modS p_modSdev e_modA e_modA_simple e_modABen e_modAbin e_modAdev e_modS e_modSdev
# 1              (Intercept)    100        100           100    100.00     15.37  100.0     28.88   2.55          2.56      0.47      0.49      0.05   1.81      0.07
# 2                scale(CN)    100        100           100      0.53      6.42  100.0      5.08   0.03          0.03      0.01      0.00      0.00   0.05      0.00
# 3             scale(DiffP)    100        100           100    100.00      9.63  100.0      6.82  -0.16         -0.14     -0.06      0.41     -0.04  -0.15     -0.01
# 4            scale(TotalP)    100         NA           100    100.00     12.30  100.0     12.97   0.46          0.43        NA     -0.15      0.02   0.67     -0.01
# 5               Typez_Obsv      0         NA            NA      0.67        NA    0.8        NA   0.00            NA        NA      0.01        NA   0.01        NA
# 6     Typez_Obsv:scale(CN)      0         NA            NA      0.00        NA    0.0        NA   0.00            NA        NA      0.00        NA   0.00        NA
# 7  Typez_Obsv:scale(DiffP)      0         NA            NA      0.40        NA    0.0        NA   0.00            NA        NA      0.00        NA   0.00        NA
# 8 Typez_Obsv:scale(TotalP)      0         NA            NA      0.27        NA    0.0        NA   0.00            NA        NA      0.00        NA   0.00        NA

# [[2]]
                    # Factor p_modA p_modA_Ben p_modA_simple p_modAbin p_modAdev p_modS p_modSdev e_modA e_modA_simple e_modABen e_modAbin e_modAdev e_modS e_modSdev
# 1              (Intercept) 100.00        100           100    100.00    100.00 100.00    100.00   2.54          2.78      0.59      0.50      4.18   1.79      3.14
# 2                scale(CN)  99.73        100           100      0.27      6.55  99.87      8.96   0.03          0.03      0.04      0.00     -0.04   0.05     -0.06
# 3             scale(DiffP) 100.00        100           100    100.00    100.00 100.00    100.00  -0.16         -0.21     -0.09      0.43     -2.10  -0.16     -1.14
# 4            scale(TotalP) 100.00         NA           100    100.00    100.00 100.00    100.00   0.48          0.52        NA     -0.16      3.98   0.70      3.18
# 5               Typez_Obsv 100.00         NA            NA    100.00        NA 100.00        NA   0.23            NA        NA      0.78        NA   0.32        NA
# 6     Typez_Obsv:scale(CN)   0.13         NA            NA     14.30        NA   0.13        NA   0.01            NA        NA      0.02        NA   0.00        NA
# 7  Typez_Obsv:scale(DiffP) 100.00         NA            NA     25.27        NA  97.73        NA  -0.06            NA        NA      0.03        NA  -0.03        NA
# 8 Typez_Obsv:scale(TotalP) 100.00         NA            NA    100.00        NA  81.55        NA   0.06            NA        NA      0.23        NA   0.03        NA

# [[3]]
                    # Factor p_modA p_modA_Ben p_modA_simple p_modAbin p_modAdev p_modS p_modSdev e_modA e_modA_simple e_modABen e_modAbin e_modAdev e_modS e_modSdev
# 1              (Intercept)    100        100           100    100.00       100 100.00       100   2.51          2.70      0.55      0.40      3.65   1.76      3.00
# 2                scale(CN)    100        100           100     55.61       100 100.00       100   0.04          0.10      0.08      0.03      0.73   0.07      0.51
# 3             scale(DiffP)    100        100           100    100.00       100 100.00       100  -0.17         -0.21     -0.08      0.36     -1.89  -0.17     -1.18
# 4            scale(TotalP)    100         NA           100    100.00       100 100.00       100   0.49          0.53        NA     -0.09      3.91   0.72      3.27
# 5               Typez_Obsv    100         NA            NA    100.00        NA 100.00        NA   0.19            NA        NA      0.59        NA   0.28        NA
# 6     Typez_Obsv:scale(CN)    100         NA            NA    100.00        NA 100.00        NA   0.06            NA        NA      0.22        NA   0.07        NA
# 7  Typez_Obsv:scale(DiffP)    100         NA            NA      7.22        NA  94.92        NA  -0.05            NA        NA      0.01        NA  -0.03        NA
# 8 Typez_Obsv:scale(TotalP)    100         NA            NA    100.00        NA  87.57        NA   0.06            NA        NA      0.27        NA   0.03        NA




}

PbLogs_sim23 # sim num where something went wrong, also seed number of those sims

{# Sim 3

# import files
fileNames3 <- list.files("Iceberg/Sim3_out") # vector of filenames
fileList3 <- lapply(paste("Iceberg/Sim3_out",fileNames3, sep="/"), read.csv) # list with one file per element named from 1 to 6000
for (i in 1:length(fileList3)) {names(fileList3)[[i]]<-gsub("\\..*","",fileNames3[i])} # change name of each element to be the sim name
fileList3 <- fileList3[!char2end(names(fileList3), "_", 2) %in% PbLogs_sim23] # remove filenames where one model did not converge in any of the four type of simulations

# select files per Sim type
fileList_Sim3_1 <- fileList3[grepl("sim3_1",names(fileList3))] 


# Number of files per sim type
NreplicatesSimulation <- length(fileList_Sim3_1) # 685

# shape results Sim 2
Results_Sim_3 <- Shape_results(fileList_Sim3_1,1) # real data randomized, real tests
Results_Sim_3
# Simulation 3: Randomized real dataset instead of generating data

                                   # Factor p_modA p_modS e_modA e_modS
# 1                             (Intercept) 100.00    100   2.70   1.95
# 2                              Typez_Obsv   0.00      0   0.00   0.01
# 3                       scale(ParentsAge) 100.00    100  -0.03  -0.04
# 4             scale(HatchingDayAfter0401)   0.00      0   0.00   0.01
# 5                      scale(PairBroodNb)   0.00      0   0.01   0.02
# 6                        ChickAgeCatAge10 100.00      0  -0.07   0.01
# 7                       scale(RelTimeHrs)  21.02      0  -0.01   0.00
# 8                     MPriorResidenceTRUE   0.00      0   0.02  -0.01
# 9                     FPriorResidenceTRUE   0.00      0  -0.01   0.01
# 10                         scale(ChickNb) 100.00    100   0.04   0.08
# 11                          scale(TotalP) 100.00    100   0.45   0.67
# 12                           scale(DiffP) 100.00    100  -0.17  -0.17
# 13           Typez_Obsv:scale(ParentsAge)   0.00      0   0.00   0.00
# 14 Typez_Obsv:scale(HatchingDayAfter0401)   0.00      0   0.00   0.00
# 15          Typez_Obsv:scale(PairBroodNb)   0.00      0   0.00   0.00
# 16            Typez_Obsv:ChickAgeCatAge10   0.00      0   0.00   0.00
# 17           Typez_Obsv:scale(RelTimeHrs)   0.00      0   0.00   0.00
# 18         Typez_Obsv:MPriorResidenceTRUE   0.00      0   0.00   0.00
# 19         Typez_Obsv:FPriorResidenceTRUE   0.00      0   0.00   0.00
# 20              Typez_Obsv:scale(ChickNb)   0.00      0   0.00   0.00
# 21               Typez_Obsv:scale(TotalP)   0.00      0   0.00   0.00
# 22                Typez_Obsv:scale(DiffP)   0.00      0   0.00   0.00

}















